exception A of int
fun f x = let exception A of int in A 1 end
